export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Title1',
        content: 'Content1',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'active',
        photo: 'https://images.pexels.com/photos/275637/pexels-photo-275637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 999,
        phone: 123456789,
        location: 'Location',
      },
      {
        id: '2',
        title: 'Title2',
        content: 'Content2',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'active',
        photo: 'Photo',
        price: 666,
        phone: 987654321,
        location: 'Location',
      },
      {
        id: '3',
        title: 'Title3',
        content: 'Content3',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'active',
        photo: 'Photo',
        price: 333,
        phone: 456123789,
        location: 'Location',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
