export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Title1',
        content: 'Content1',
        publicationDate: '05.01.2020',
        lastUpdate: '05.01.2020',
        email: 'Email',
        status: 'active',
        photo: 'https://images.pexels.com/photos/275637/pexels-photo-275637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        price: 999,
        phone: 123456789,
        location: 'Location',
        userId: '2',
      },
      {
        id: '2',
        title: 'Title2',
        content: 'Content2',
        publicationDate: '01.01.2020',
        lastUpdate: '01.01.2020',
        email: 'Email',
        status: 'active',
        photo: 'Photo',
        price: 666,
        phone: 987654321,
        location: 'Location',
        userId: '3',
      },
      {
        id: '3',
        title: 'Title3',
        content: 'Content3',
        publicationDate: '09.23.2020',
        lastUpdate: '09.23.2020',
        email: 'Email',
        status: 'active',
        photo: 'Photo',
        price: 333,
        phone: 456123789,
        location: 'Location',
        userId: '2',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  users: [
    {
      id: '1',
      name: 'admin',
      permission: 'admin',
    },
    {
      id: '2',
      name: 'user1',
      permission: 'user',
    },
    {
      id: '3',
      name: 'user2',
      permission: 'user',
    },
    {
      id: '4',
      name: 'not logged user',
      permission: 'not authorized',
    },
  ],
};
