export const initialState = {
  posts: {
    data: [
      {
        id: 1,
        title: 'Title1',
        content: 'Content1',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'Status',
        photo: 'Photo',
        price: 999,
        phone: 123456789,
        location: 'Location',
      },
      {
        id: 2,
        title: 'Title2',
        content: 'Content2',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'Status',
        photo: 'Photo',
        price: 666,
        phone: 987654321,
        location: 'Location',
      },
      {
        id: 3,
        title: 'Title3',
        content: 'Content3',
        publicationDate: 'Publication date',
        lastUpdate: 'Last update date',
        email: 'Email',
        status: 'Status',
        photo: 'Photo',
        price: 333,
        phone: 456123789,
        location: 'Location',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
